### ISSUE TITLE
Use Rails native DB encryption

### ISSUE THREAD

**Issue by jlecour** [ezekg/example-rails-api-key-authentication#1]
Hi,

I've enjoyed reading your article and applying the code to side project of mine. Thanks for writting this down for others to learn.

I've noticed that with Rails 7 native DB encryption feature, we can simplify the token encryption.

We need to generate the keys with `$ bin/rails db:encryption:init` and store the resul in the cedentials with `$ bin/rails credentials:edit`.

The migration must be changed to : 

```ruby
class CreateApiKeys < ActiveRecord::Migration[7.0]
  def up
    create_table :api_keys do |t|
      t.string :token
      t.references :bearer, polymorphic: true, null: false
    end

    add_index :api_keys, [:bearer_id, :bearer_type]
    add_index :api_keys, :token, unique: true
  end

  def down
    drop_table :api_keys
  end
end
```

and the `ApiKey` model can be reduced to this : 

```ruby
class ApiKey < ApplicationRecord
  encrypts :token, deterministic: true

  belongs_to :bearer, polymorphic: true

  def self.authenticate_by_token!(token)
    find_by! token: token
  end

  def self.authenticate_by_token(token)
    authenticate_by_token! token
  rescue ActiveRecord::RecordNotFound
    nil
  end
end
```

There is nothing to deal with for storing the HMAC key, no manual digest storage, cleaning, swapping…

**Comment by ezekg** [comment]
This actually is quite different than an HMAC. Your solution utilizes encryption instead of hashing, which means API keys can be read after creation. Typically, you'd want to use a one-way hash, e.g. an HMAC, so that the token can only be read after creation. But if that's not a big deal, then this is a great solution.

For example, encryption would be great for API keys that behaved kind of like Stripe secret keys, since those can be read again after generating the key (meaning they're encrypted, not hashed.)

**Comment by jlecour** [comment]
Hi @ezekg. Thanks for clarifying that big difference.

I can see many use cases where it's usefull to be able to read the token afterwards, and some cases where it would be necessary to have it unreadable.
